### ISSUE TITLE
calling seneca.close throws an error

### ISSUE THREAD

**Issue by benbenbenbenbenben** [disintegrator/seneca-amqp-transport#16] opened 2016-03-10 12:26 UTC
I have an integration script that used to use the default transport. Now I have migrated to seneca-amqp-transport, there is an error client side when I try to close the connection and exit the script. The channel is already closing.

`IllegalOperationError: Connection closing`

I won't post the whole thing, but the line(s) causing the problem starts on line 82 in client-hook.js

**Comment by nfantone** [comment] 2016-03-10 14:32
@benbenbenbenbenben Strange. Never seen this before. Could you post a simple snippet where the issue is reproduced, please?

Thanks for taking the time to let us know.

**Comment by nfantone** [comment] 2016-03-11 02:53
@benbenbenbenbenben Been digging around and found out that the issue has to do with the `.close` method on channel and connection objects on [amqplib](http://www.squaremobius.net/amqp.node/channel_api.html#channel_close) not being idempotent. Also, there is currently no way of determining their state (closed or closing). [There is a proposal for such an API](https://github.com/squaremo/amqp.node/issues/111#issuecomment-69464994) but no there has been no news for a while.

While I'm at it, I should mention that, from the way you phrased it:

> when I try to close the connection and exit the script.

It sounds like you are trying to close resources manually, somehow. You don't have to do that. The transport will take care of that on seneca shutdown.

**Closed** 2016-03-16 02:44 UTC
Labels: wontfix

**Comment by benbenbenbenbenben** [comment] 2016-03-18 15:07
Thanks @nfantone - I haven't been around on github lately so I missed your question about a snippet.

It was occurring in a initialisation script. If I didn't have `seneca.close` at the end, the script would not exit. Perhaps an explicit `process.exit` makes better sense in hindsight. Nevertheless; to reproduce:

```javascript
"use strict"
var async = require('async');
var seneca = require('seneca')().use('seneca-amqp-transport');
seneca.client({type:'amqp', pins:['data:*', 'data_test:*']});

async.series([
  done => {
     // do stuff
    done();  
  },
  done => {
    // do stuff
    done();
  }
], error => {
  if (error)
    throw error;
  seneca.close();
});
// eof
```

**Comment by nfantone** [comment] 2016-03-18 16:11
@benbenbenbenbenben I tried your script (with ` url:'amqp://dev.rabbitmq.com'` on the options) and I failed to reproduce the error. Aside from that, I see that the `seneca.close()` won't be called if something error'd before - consider moving that to a `finally` block or a `process.once` to listen for shutdown signals.

I have something like this in many of my projects:

```js
function shutdown() {
  seneca.close();
  log.warn('Closing down seneca instance');
}
process.once('SIGINT', shutdown);
process.once('SIGTERM', shutdown);
```
